image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/

stages:
  - dockerize

dockerize:
  stage: dockerize
  script:
    - docker build -t bungie-manifest-updater:0.1.0 .
